- hosts: localhost
  become: yes
  gather_facts: no

  tasks:

  - name: Make OS Tweaks
    ansible.builtin.include_tasks:
      file: os/tweaks.yaml

  - name: Make Audio Tweaks
    ansible.builtin.include_tasks:
      file: os/audio.yaml

  - name: Adding dpkg armhf architecture
    ansible.builtin.shell:
      cmd: dpkg --add-architecture armhf

  - name: Dist upgrade
    ansible.builtin.apt:
      update_cache: yes
      upgrade: dist

  - name: Uninstall packages
    ansible.builtin.apt:
      state: absent
      pkg:
      - indicator-multiload
      - chromium-browser
      - firefox

  - name: Auto remove un-needed packages
    ansible.builtin.apt:
      autoremove: yes

  - name: Auto clean
    ansible.builtin.apt:
      autoclean: yes

  - name: Install Standard Packages
    ansible.builtin.apt:
      state: present
      pkg:
      - vim
      - fzf
      - build-essential
      - cmake
      - pi-bluetooth
      - raspi-config

  - name: Install Chrome (can't do this as it's only amd64, NOT arm64)
    ansible.builtin.include_tasks: 
      file: softwares/chromium.yaml
    when: no

  - name: Install VSCode
    ansible.builtin.include_tasks:
      file: softwares/vscode.yaml
    when: no
  
  - name: Install i3
    ansible.builtin.include_tasks:
      file: softwares/i3.yaml
    when: yes

  - name: Install nix
    ansible.builtin.include_tasks:
      file: softwares/nix.yaml
    when: yes
      
  - name: Install nix packages
    ansible.builtin.include_tasks:
      file: softwares/nix-packages.yaml
    when: yes

  - name: Add Chromium sync workaround
    ansible.builtin.include_tasks:
      file: softwares/chromium-sync-workaround.yaml
    when: no #Not working, chromium doesn't sync with this

  - name: Add Citrix
    ansible.builtin.include_tasks:
      file: softwares/citrix.yaml
    when: yes

  - name: Build & Install box86
    ansible.builtin.include_tasks:
      file: softwares/box86.yaml
    when: no

  - name: Build & Install box64
    ansible.builtin.include_tasks:
      file: softwares/box64.yaml
    when: no

  - name: Zoom
    ansible.builtin.include_tasks:
      file: softwares/zoom.yaml
    when: no

