- name: Get i3 key deb
  ansible.builtin.get_url:
    url: https://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2022.02.17_all.deb
    checksum: sha256:52053550c4ecb4e97c48900c61b2df4ec50728249d054190e8a0925addb12fc6
    dest: /tmp
  register: i3_download

- name: Add i3 keyring to dpkg
  ansible.builtin.shell:
    cmd: dpkg -i {{ i3_download.dest }}

- name: Generate i3 repo line
  ansible.builtin.shell:
    cmd: echo "deb http://debian.sur5r.net/i3/ $(grep '^DISTRIB_CODENAME=' /etc/lsb-release | cut -f2 -d=) universe"
  register: repo_line

- name: Generated repo line output
  ansible.builtin.debug:
    var: repo_line.stdout

- name: Add i3 repo
  ansible.builtin.lineinfile:
    state: present
    create: yes
    regexp: '^.*debian\.sur5r\.net/i3.*$'
    line: "{{ repo_line.stdout }}"
    path: "/etc/apt/sources.list.d/sur5r-i3.list"

- name: Install i3
  ansible.builtin.apt:
    state: present
    update_cache: yes
    pkg:
    - i3

