# See instructions at: https://pimylifeup.com/raspberry-pi-zoom/
- name: Install Zoom Deps
  ansible.builtin.apt:
    state: present
    pkg:
    - libxcb-xtest0
    - libxcb-xtest0:armhf
    - libxcb-shape0
    - libxcb-shape0:armhf
    - libxcb-image0
    - libxcb-image0:armhf
    - libxcb-keysyms1
    - libxcb-keysyms1:armhf
    - libxtst6
    - libxtst6:armhf
    - libcanberra-gtk3-module
    - libcanberra-gtk3-module:armhf

- name: Install Zoom (Enable to download and install locally)
  become: no
  when: yes
  delegate_to: localhost
  vars:
    zoom_arch: zoom_x86_64
    zoom_version: 5.11.10.4400
    box: BOX64
    #zoom_arch: zoom_i686
    #zoom_version: 5.4.53391.1108
    #box: BOX86
    desktop_file: ~/.local/share/applications
    desktop_contents: |-
      [Desktop Entry]
      Encoding=UTF-8
      Name=Zoom (Ansible Managed)
      Exec={{ home_directory.stdout }}/zoom/{{ zoom_arch }}/zoom/runZoom %U
      Icon={{ home_directory.stdout }}/.local/share/applications/zoom.png
      Type=Application
      Terminal=false
      Categories=Network;Application;
      MimeType=x-scheme-handler/zoommtg;x-scheme-handler/zoomus;x-scheme-handler/tel;x-scheme-handler/callto;x-scheme-handler/zoomphonecall;application/x-zoom
      StartupWMClass=zoom
      X-KDE-Protocols=zoommtg;zoomus;tel;callto;zoomphonecall;
    launch_script_contents: |-
      #!/bin/bash
      cd {{ home_directory.stdout }}/zoom/{{ zoom_arch }}/zoom
      {{ box }}_LD_LIBRARY_PATH=./:./cef ./ZoomLauncher "$@"

  block:

    - name: Get home directory
      ansible.builtin.shell:
        cmd: echo ~
      register: home_directory

    - name: Make zoom directory
      ansible.builtin.file:
        state: directory
        dest: ~/zoom

    - name: Download zoom tar
      ansible.builtin.get_url:
        url: https://zoom.us/client/{{ zoom_version }}/{{ zoom_arch }}.tar.xz
        dest: ~/zoom

    - name: Remove extraction directory
      ansible.builtin.file:
        state: absent
        dest: ~/zoom/{{ zoom_arch }}

    - name: Make extraction directory
      ansible.builtin.file:
        state: directory
        dest: ~/zoom/{{ zoom_arch }}

    - name: Extract zoom tar
      ansible.builtin.unarchive:
        src: ~/zoom/{{ zoom_arch }}.tar.xz
        dest: ~/zoom/{{ zoom_arch }}

    - name: Generate Zoom Desktop file
      ansible.builtin.copy:
        content: "{{ desktop_contents }}"
        dest: "~/.local/share/applications/zoom.desktop"
        force: yes

    - name: Set up embedded browser configuration
      ansible.builtin.lineinfile:
        path: ~/.config/zoomus.conf
        create: true
        line: "{{ item }}"
        state: present
        regex: ^{{ item }}
      loop:
        - "embeddedBrowserForFacebookLogin=true"
        - "embeddedBrowserForGoogleLogin=true"
        - "embeddedBrowserForSSOLogin=true"

    - name: Create Zoom Launch File
      ansible.builtin.copy:
        content: "{{ launch_script_contents }}"
        dest: ~/zoom/{{ zoom_arch }}/zoom/runZoom
        force: yes
        mode: a+rx,g+rx,u+rwx

